# glib-networking Italian translation
# Copyright (C) 2011, 2012, 2013, 2016, 2017, 2018, 2019 Free Software Foundation, Inc
# This file is distributed under the same license as the glib-networking package.
# Luca Ferretti <lferrett@gnome.org>, 2011, 2012.
# Milo Casagrande <milo@ubuntu.com>, 2013, 2017, 2018, 2019.
# Gianvito Cavasoli <gianvito@gmx.it>, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: glib-networking\n"
"Report-Msgid-Bugs-To: https://gitlab.gnome.org/GNOME/glib-networking/issues\n"
"POT-Creation-Date: 2019-07-04 09:53+0000\n"
"PO-Revision-Date: 2019-08-20 10:38+0200\n"
"Last-Translator: Milo Casagrande <milo@milo.name>\n"
"Language-Team: Italiano <gnome-it-list@gnome.org>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 2.2.3\n"

#: proxy/libproxy/glibproxyresolver.c:159
msgid "Proxy resolver internal error."
msgstr "Errore interno del resolver proxy."

#: tls/base/gtlsconnection-base.c:479 tls/base/gtlsinputstream.c:78
#: tls/base/gtlsinputstream.c:141 tls/base/gtlsoutputstream.c:78
#: tls/base/gtlsoutputstream.c:143
msgid "Connection is closed"
msgstr "La connessione è chiusa"

#. Cannot perform a blocking operation during a handshake on the
#. * same thread that triggered the handshake. The only way this can
#. * occur is if the application is doing something weird in its
#. * accept-certificate callback. Allowing a blocking op would stall
#. * the handshake (forever, if there's no timeout). Even a close
#. * op would deadlock here.
#.
#: tls/base/gtlsconnection-base.c:549
msgid "Cannot perform blocking operation during TLS handshake"
msgstr "Impossibile eseguire un'operazione bloccante durante l'handshake TLS"

#: tls/base/gtlsconnection-base.c:612 tls/base/gtlsconnection-base.c:1118
msgid "Socket I/O timed out"
msgstr "I/O sul socket scaduto"

#: tls/base/gtlsconnection-base.c:1339
msgid "Peer does not support safe renegotiation"
msgstr "Il nodo non supporto la rinegoziazione sicura"

#: tls/base/gtlsconnection-base.c:1382
msgid "Server required TLS certificate"
msgstr "Il server richiede un certificato TLS"

#: tls/base/gtlsconnection-base.c:1477 tls/gnutls/gtlsconnection-gnutls.c:419
#: tls/openssl/gtlsconnection-openssl.c:172
#, c-format
msgid "Unacceptable TLS certificate"
msgstr "Certificato TLS inammissibile"

#: tls/base/gtlsconnection-base.c:1884
#, c-format
msgid "Receive flags are not supported"
msgstr "I flag di ricezione non sono supportati"

#: tls/base/gtlsconnection-base.c:2019
#, c-format
msgid "Send flags are not supported"
msgstr "I flag di invio non sono supportati"

#: tls/gnutls/gtlscertificate-gnutls.c:178
#: tls/openssl/gtlscertificate-openssl.c:170
#, c-format
msgid "Could not parse DER certificate: %s"
msgstr "Impossibile analizzare il certificato DER: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:199
#: tls/openssl/gtlscertificate-openssl.c:190
#, c-format
msgid "Could not parse PEM certificate: %s"
msgstr "Impossibile analizzare il certificato PEM: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:230
#: tls/openssl/gtlscertificate-openssl.c:209
#, c-format
msgid "Could not parse DER private key: %s"
msgstr "Impossibile analizzare la chiave privata DER: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:261
#: tls/openssl/gtlscertificate-openssl.c:228
#, c-format
msgid "Could not parse PEM private key: %s"
msgstr "Impossibile analizzare la chiave privata PEM: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:297
#: tls/openssl/gtlscertificate-openssl.c:263
msgid "No certificate data provided"
msgstr "Nessun dato di certificato fornito"

#: tls/gnutls/gtlsconnection-gnutls.c:224
#: tls/openssl/gtlsclientconnection-openssl.c:522
#: tls/openssl/gtlsserverconnection-openssl.c:399
#, c-format
msgid "Could not create TLS connection: %s"
msgstr "Impossibile creare la connessione TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:353
#: tls/gnutls/gtlsconnection-gnutls.c:364
#: tls/gnutls/gtlsconnection-gnutls.c:388
#: tls/openssl/gtlsconnection-openssl.c:139
#, c-format
msgid "Peer failed to perform TLS handshake: %s"
msgstr "Il nodo non è stato in grado di eseguire l'handshake TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:375
#: tls/openssl/gtlsconnection-openssl.c:248
msgid "Peer requested illegal TLS rehandshake"
msgstr "Il nodo ha richesto un re-handshake non lecito"

#: tls/gnutls/gtlsconnection-gnutls.c:396
msgid "TLS connection closed unexpectedly"
msgstr "La connessione TLS si è chiusa in modo inatteso"

#: tls/gnutls/gtlsconnection-gnutls.c:411
#: tls/openssl/gtlsconnection-openssl.c:164
msgid "TLS connection peer did not send a certificate"
msgstr "Il nodo di connessione TLS non ha inviato un certificato"

#: tls/gnutls/gtlsconnection-gnutls.c:427
#, c-format
msgid "Peer sent fatal TLS alert: %s"
msgstr "Il nodo ha inviato un avviso TLS fatale: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:437
msgid "Protocol version downgrade attack detected"
msgstr "Rilevato attacco di declassamento del protocollo di versione"

#: tls/gnutls/gtlsconnection-gnutls.c:446
#, c-format
msgid "Message is too large for DTLS connection; maximum is %u byte"
msgid_plural "Message is too large for DTLS connection; maximum is %u bytes"
msgstr[0] ""
"Il messaggio è troppo grande per una connessione DTLS (massimo %u byte)"
msgstr[1] ""
"Il messaggio è troppo grande per una connessione DTLS (massimo %u byte)"

#: tls/gnutls/gtlsconnection-gnutls.c:455
msgid "The operation timed out"
msgstr "Tempo esaurito per l'operazione"

#: tls/gnutls/gtlsconnection-gnutls.c:780
#, c-format
msgid "Error performing TLS handshake: %s"
msgstr "Errore nell'eseguire l'handshake TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:883
#: tls/openssl/gtlsconnection-openssl.c:257
#: tls/openssl/gtlsconnection-openssl.c:307
msgid "Error performing TLS handshake"
msgstr "Errore nell'eseguire l'handshake TLS"

#: tls/gnutls/gtlsconnection-gnutls.c:929
#: tls/gnutls/gtlsconnection-gnutls.c:989
#: tls/openssl/gtlsconnection-openssl.c:414
msgid "Error reading data from TLS socket"
msgstr "Errore nel leggere dati dal socket TLS"

#. flags
#: tls/gnutls/gtlsconnection-gnutls.c:1011
#: tls/gnutls/gtlsconnection-gnutls.c:1075
#: tls/openssl/gtlsconnection-openssl.c:458
msgid "Error writing data to TLS socket"
msgstr "Errore nello scrivere dati sul socket TLS"

#: tls/gnutls/gtlsconnection-gnutls.c:1045
#, c-format
msgid "Message of size %lu byte is too large for DTLS connection"
msgid_plural "Message of size %lu bytes is too large for DTLS connection"
msgstr[0] "Un messaggio di %lu byte è troppo grande per la connessione DTLS"
msgstr[1] "Un messaggio di %lu byte è troppo grande per la connessione DTLS"

#: tls/gnutls/gtlsconnection-gnutls.c:1047
#, c-format
msgid "(maximum is %u byte)"
msgid_plural "(maximum is %u bytes)"
msgstr[0] "(massimo %u byte)"
msgstr[1] "(massimo %u byte)"

#: tls/gnutls/gtlsconnection-gnutls.c:1094
#, c-format
msgid "Error performing TLS close: %s"
msgstr "Errore nell'eseguire la chiusura TLS: %s"

#: tls/gnutls/gtlsdatabase-gnutls.c:553
msgid ""
"Failed to load system trust store: GnuTLS was not configured with a system "
"trust"
msgstr ""
"Caricamento dell'archivio di attendibilità di sistema non riuscito: GnuTLS "
"non è stato configurato con un archivio di attendibilità di sistema"

#: tls/gnutls/gtlsdatabase-gnutls.c:558 tls/openssl/gtlsdatabase-openssl.c:187
#, c-format
msgid "Failed to load system trust store: %s"
msgstr "Caricamento dell'archivio di attendibilità di sistema non riuscito: %s"

#: tls/gnutls/gtlsserverconnection-gnutls.c:137
#: tls/openssl/gtlsserverconnection-openssl.c:90
msgid "Certificate has no private key"
msgstr "Il certificato non presenta chiave privata"

#: tls/openssl/gtlsclientconnection-openssl.c:412
#: tls/openssl/gtlsclientconnection-openssl.c:469
#: tls/openssl/gtlsserverconnection-openssl.c:288
#: tls/openssl/gtlsserverconnection-openssl.c:339
#, c-format
msgid "Could not create TLS context: %s"
msgstr "Impossibile creare il contesto TLS: %s"

#: tls/openssl/gtlsconnection-openssl.c:180
#, c-format
msgid "Unacceptable TLS certificate authority"
msgstr "Autorità certificato TLS inammissibile"

#: tls/openssl/gtlsconnection-openssl.c:188
msgid "Digest too big for RSA key"
msgstr "Digest troppo grande per una chiave RSA"

#: tls/openssl/gtlsconnection-openssl.c:495
msgid "Error performing TLS close"
msgstr "Errore nell'eseguire la chiusura TLS"

#: tls/openssl/gtlsdatabase-openssl.c:227
msgid "Could not create CA store"
msgstr "Impossibile creare l'archivio CA"

#: tls/openssl/gtlsfiledatabase-openssl.c:454
#, c-format
msgid "Failed to load file path: %s"
msgstr "Caricamento del percorso del file non riuscito: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:101
#, c-format
msgid "There is a problem with the certificate: %s"
msgstr "C'è un problema con il certificato: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:109
#, c-format
msgid "There is a problem with the certificate private key: %s"
msgstr "C'è un problema con la chiave privata del certificato: %s"
